### ISSUE TITLE
Install fail! Error: Unsupported URL Type: npm:enzyme-react-adapter-future

### ISSUE THREAD

**Issue by suhangdev** [guonanci/react-images-viewer#24]
https://github.com/guonanci/react-images-viewer/blob/master/package.json#L96

![image](https://user-images.githubusercontent.com/25616926/118938832-a5e37880-b981-11eb-838f-e93d34457885.png)

**Comment by guonanci** [comment]
> https://github.com/guonanci/react-images-viewer/blob/master/package.json#L96
> 
> ![image](https://user-images.githubusercontent.com/25616926/118938832-a5e37880-b981-11eb-838f-e93d34457885.png)

Fixed in react-images-viewer@v1.6.5 ("enzyme-adapter-react-16": "^1.15.6"), check it ?

**Comment by suhangdev** [comment]
LGTM
