### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'srcSet')

### ISSUE THREAD

**Issue by EdKo2001** [guonanci/react-images-viewer#36]
Hello, Could you please help what is wrong with clicking next and prev images? Clicking on the thumbnails works fine and after clicking on it next and prev images work fine.
Below is my code.
Thx in advance!

           const closeImgsViewer = () => {
                setState({
                  currImg: 0,
                  isOpen: false,
                });
              };

              const gotoPrevImg = () => {
                setState((prevStates) => ({
                  ...prevStates,
                  currImg: prevStates.currImg - 1,
                }));
              };
              const gotoNextImg = () => {
                setState((prevStates) => ({
                  ...prevStates,
                  currImg: state.currImg + 1,
                }));
              };

              const gotoImg = (index) => {
                setState((prevStates) => ({
                  ...prevStates,
                  currImg: index,
                }));
              };

              const openImgsViewer = (index, event) => {
                event.preventDefault();
                setState((prevStates) => ({
                  ...prevStates,
                  currImg: index,
                  isOpen: true,
                }));
              };

              return (
                <div
                  className="capstone-gallery"
                  key={`capstone-gallery${idx}`}
                >
                  <div className="wrap-image-gallery">
                    <ImageGallery
                      items={swatches}
                      showThumbnails={swatches.length > 1 ? true : false}
                      showNav={false}
                      showPlayButton={false}
                      showFullscreenButton={false}
                      useBrowserFullscreen={false}
                      // renderCustomControls={customFullScreenButton}
                      ref={currentIndexRef}
                      onClick={() => setState({ isOpen: true })}
                    />
                  </div>
                  <div className="capstone-gallery-content">
                    <h6>{gallery.title}</h6>
                    <p>{gallery.description}</p>
                    <a href={gallery.link_url}>
                      {gallery.link_text}
                      <span className="icon-right-arrow" />
                    </a>
                  </div>
                  <ImgsViewer
                    imgs={modalImages}
                    srcset={swatches}
                    currImg={state.currImg}
                    showThumbnails={true}
                    isOpen={state.isOpen}
                    onClickPrev={gotoPrevImg}
                    onClickNext={gotoNextImg}
                    onClickThumbnail={gotoImg}
                    onClose={closeImgsViewer}
                    onClick={openImgsViewer}
                    backdropCloseable
                  />

**Comment by EdKo2001** [comment]
![image](https://user-images.githubusercontent.com/53624093/135452186-a6cccf2c-d701-42b9-9ba3-ebce1427e06f.png)

**Comment by guonanci** [comment]
Same reason as issue#37, it's your `idx`  get_value problem, the cmpt can not get the image data
