### ISSUE TITLE
After opening the lightbox the .fade div has opacity 0

### ISSUE THREAD

**Issue by EdKo2001** [guonanci/react-images-viewer#37]
Hello, Could you please help after opening the lightbox the .fade div has opacity 0 ?
Below is my code.
Thx in advance!

![image](https://user-images.githubusercontent.com/53624093/135447297-274dc752-1c10-433f-90ed-4cb922aa298a.png)

           const closeImgsViewer = () => {
                setState({
                  currImg: 0,
                  isOpen: false,
                });
              };

              const gotoPrevImg = () => {
                setState((prevStates) => ({
                  ...prevStates,
                  currImg: prevStates.currImg - 1,
                }));
              };
              const gotoNextImg = () => {
                setState((prevStates) => ({
                  ...prevStates,
                  currImg: state.currImg + 1,
                }));
              };

              const gotoImg = (index) => {
                setState((prevStates) => ({
                  ...prevStates,
                  currImg: index,
                }));
              };

              const openImgsViewer = (index, event) => {
                event.preventDefault();
                setState((prevStates) => ({
                  ...prevStates,
                  currImg: index,
                  isOpen: true,
                }));
              };

              return (
                <div
                  className="capstone-gallery"
                  key={`capstone-gallery${idx}`}
                >
                  <div className="wrap-image-gallery">
                    <ImageGallery
                      items={swatches}
                      showThumbnails={swatches.length > 1 ? true : false}
                      showNav={false}
                      showPlayButton={false}
                      showFullscreenButton={false}
                      useBrowserFullscreen={false}
                      // renderCustomControls={customFullScreenButton}
                      ref={currentIndexRef}
                      onClick={() => setState({ isOpen: true })}
                    />
                  </div>
                  <div className="capstone-gallery-content">
                    <h6>{gallery.title}</h6>
                    <p>{gallery.description}</p>
                    <a href={gallery.link_url}>
                      {gallery.link_text}
                      <span className="icon-right-arrow" />
                    </a>
                  </div>
                  <ImgsViewer
                    imgs={modalImages}
                    srcset={swatches}
                    currImg={state.currImg}
                    showThumbnails={true}
                    isOpen={state.isOpen}
                    onClickPrev={gotoPrevImg}
                    onClickNext={gotoNextImg}
                    onClickThumbnail={gotoImg}
                    onClose={closeImgsViewer}
                    onClick={openImgsViewer}
                    backdropCloseable
                  />

**Comment by guonanci** [comment]
Your `openImgsViewer` method isn't used correctly, cause there's no `idx` value, it's your codebase's problem

**Comment by professional-people** [comment]
I am also facing the same issue the fade class has 0 opacity. Please help.

**Comment by FozanGardezi** [comment]
I am also having this issue, a class fade is assigned to the div and it has opacity 0.
