### ISSUE TITLE
Can't install your plugin

### ISSUE THREAD

**Issue by ioszhuk** [guonanci/react-images-viewer#38]
**Steps to reproduce the behavior:**

I used to react@17.0.2 and I can't install your plugin - screenshot: http://joxi.ru/xAeb6VqUb448qr

**Expected behavior:**

**Actual behavior:**

**Comment by alissontenorio** [comment]
I have the same problem

**Comment by AnonySharma** [comment]
> **Steps to reproduce the behavior:**
> 
> I used to react@17.0.2 and I can't install your plugin - screenshot: http://joxi.ru/xAeb6VqUb448qr
> 
> **Expected behavior:**
> 
> **Actual behavior:**

The github.io page for this repo has a different package name, try that, maybe it'll work.
[https://guonanci.github.io/react-images-viewer/](https://guonanci.github.io/react-images-viewer/)

`npm install react-images --save`

**Comment by chriswales95** [comment]
Same issue.
