### ISSUE TITLE
"Can't resolve '../icons/ArrowLeft'", and the other files inside '../icons/'

### ISSUE THREAD

**Issue by felipe-perestrelo** [guonanci/react-images-viewer#39]
Upon trying to build the project, the following error came up:
Module not found: Error: Can't resolve '../icons/ArrowLeft' in '/tmp/build_2ac2dda5/node_modules/react-images-viewer/lib/components'
@ ./node_modules/react-images-viewer/lib/components/Icon.js 17:17-46

The build failed due to this reason.

Inside **icons** folder, the files are named like **arrowLeft** (first letter lowercase), but in the **Icons.js** file, they are required as **ArrowLeft** (first letter uppercase).

I believe this happened between version 1.6.7 and 1.6.8, that wat just released, as it was running ok before yesterday.

**Comment by efendi-klb** [comment]
same here using 1.6.7 the uppercase issue when npm run build

**Comment by hulkyuan** [comment]
大哥 ，大小写路径要修改一下，作者快更新一下icons/arrowLeft.js ->icons/ArrowLeft.js 几个文件都有问题

**Comment by alexiakattah** [comment]
Aqui também estou com o mesmo problema. Qual a versão está estável?

**Comment by veeramarni** [comment]
Not sure when there will be fix to it? I'm reverting to 1.6.7

**Comment by guonanci** [comment]
Feel so sorry, I change these two file names and imports to `arrow_left, _right` @1.6.9, try 'yarn` again, I didn't find this  problem when I tested examples  on my mac before

**Comment by guonanci** [comment]
Is it ok? We need to close this issue.

**Comment by huyjs9** [comment]
It still has this issue with `Close` icon in v1.6.9
Module not found: Error: Can't resolve '../icons/Close' in '/home/kittbui/Web/op3n-admin-web/node_modules/react-images-viewer/lib/components'

**Comment by huyjs9** [comment]
It still has this issue with `Close` icon in v1.6.9
Module not found: Error: Can't resolve '../icons/Close' in '...'

**Comment by guonanci** [comment]
> It still has this issue with `Close` icon in v1.6.9 Module not found: Error: Can't resolve '../icons/Close' in '...'

solved in @1.7.0

**Comment by huyjs9** [comment]
I have found the other issue
Module build failed: Error: ENOENT: no such file or directory, open '.../node_modules/react-images-viewer/lib/ImgsViewer.js'
I see ImgsViewer.js in folder src but in package.json file, you have composed `"main": "lib/ImgsViewer.js"`

**Comment by guonanci** [comment]
> I have found the other issue Module build failed: Error: ENOENT: no such file or directory, open '.../node_modules/react-images-viewer/lib/ImgsViewer.js' I see ImgsViewer.js in folder src but in package.json file, you have composed `"main": "lib/ImgsViewer.js"`

Try again?

**Comment by huyjs9** [comment]
It solved in @1.7.1
