### ISSUE TITLE
Can't display

### ISSUE THREAD

**Issue by avillarubia2** [guonanci/react-images-viewer#6]
**Steps to reproduce the behavior:**
```
import React from 'react'
import ImgsViewer from 'react-images-viewer'
import bg from './../images/background.jpg'

const ImageViewer = () => {
    return <>
        <ImgsViewer
            imgs={[{ src: bg }]}
        />
    </>
}

export default ImageViewer
```

**Expected behavior:**
To display the image but using the sample above can't

**Actual behavior:**
The sample above can't display

**Version**
react: 16.12.0
react-images-viewer: 1.6.2

Good day,

Your tool is simple yet perfect. I am interested to use this if successful. Did I miss something that I can't display the image? The image is available and I can display it using <img> inside this component

Thank you.

**Comment by guonanci** [comment]
Using TypeScript?

**Comment by guonanci** [comment]
Did you forget to add `isOpen` prop, if you need more control, please see: react-images-viewer/examples/src/components/Gallery.js

**Comment by guonanci** [comment]
I'm so sorry that too late answering your question
